//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckRule
    {
        public int ID { get; set; }
        public string Url { get; set; }
        public string RegIp { get; set; }
        public string RegPort { get; set; }
        public string RegAnonymous { get; set; }
        public string RegType { get; set; }
        public string RegCountry { get; set; }
        public string RegProvince { get; set; }
        public string RegCity { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public Nullable<int> DeleteId { get; set; }
        public Nullable<int> IsValid { get; set; }
    }
}
