//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpPrice
    {
        public int ID { get; set; }
        public double Price { get; set; }
        public double Discount { get; set; }
        public int UseTime { get; set; }
        public string Description { get; set; }
        public string PicPath { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public Nullable<int> DeleteID { get; set; }
    }
}
