//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionInfo
    {
        public int ID { get; set; }
        public string VersionNumber { get; set; }
        public string VersionAddress { get; set; }
        public string PartName { get; set; }
        public string PartType { get; set; }
        public int PartOwner { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public Nullable<int> DeleteID { get; set; }
    }
}
