//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPSInfo
    {
        public int ID { get; set; }
        public string RAM { get; set; }
        public string Cpu { get; set; }
        public int IsOpen { get; set; }
        public string HostName { get; set; }
        public string SerialNumber { get; set; }
        public string IPIn { get; set; }
        public string IPOut { get; set; }
        public string adminstrator { get; set; }
        public string password { get; set; }
        public string KDUser { get; set; }
        public string KDPassword { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public Nullable<int> DeleteID { get; set; }
    }
}
